### ISSUE TITLE
App is not running in Mac OS 10.14 

### ISSUE THREAD

**Issue by haricharanbole** [laanlabs/FootRenderer#1]
Build was successful. When the app is running only two images were visible in the app window. App is stuck after the second image is displayed. I couldn't see any images in output directory. 

Below is the log. Also, there's a build time issue. 

> 2019-10-10 14:56:52.341452+0530 FootRenderer[34348:3253621] [DYMTLInitPlatform] platform initialization successful
> 2019-10-10 14:56:52.483319+0530 FootRenderer[34348:3253199] Metal GPU Frame Capture Enabled
> 2019-10-10 14:56:52.484058+0530 FootRenderer[34348:3253199] Metal API Validation Enabled
> Saving output to: file:///Users/a872414/Downloads/FootRenderer/output/
> [processQueue(0)] preparing scene
> scene is prepared: true
> taking snapshot

*******************************************************
**Build time issue:**

Copy SceneKit assets /Users/a872414/Downloads/FootRenderer/FootRenderer/Render/art.scnassets (in target 'FootRenderer' from project 'FootRenderer')
    cd /Users/a872414/Downloads/FootRenderer
    /Applications/Xcode.app/Contents/Developer/usr/bin/copySceneKitAssets /Users/a872414/Downloads/FootRenderer/FootRenderer/Render/art.scnassets -o /Users/a872414/Library/Developer/Xcode/DerivedData/FootRenderer-cnjerabgjsxlsrergpduhrtaotho/Build/Products/Debug/FootRenderer.app/Contents/Resources/art.scnassets --target-platform=macosx --target-version=10.14 --target-build-dir=/Users/a872414/Library/Developer/Xcode/DerivedData/FootRenderer-cnjerabgjsxlsrergpduhrtaotho/Build/Products/Debug --resources-folder-path=FootRenderer.app/Contents/Resources

dyld: Library not loaded: /usr/local/lib/libwep
  Referenced from: /usr/bin/xcrun
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libwep: code signature in (/usr/local/lib/libwep) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/lib/libwep: stat() failed with errno=1
copySceneKitAssets: Copy leg_toe_texture.png
copySceneKitAssets: Copy .DS_Store
copySceneKitAssets: Copy leg.png
copySceneKitAssets: Copy leg.scn
copySceneKitAssets: Copy floor.jpg
copySceneKitAssets: Copy clothed_toe_texture.png
copySceneKitAssets: Running scntool on /Users/a872414/Library/Developer/Xcode/DerivedData/FootRenderer-cnjerabgjsxlsrergpduhrtaotho/Build/Products/Debug/FootRenderer.app/Contents/Resources/art.scnassets/leg.scn
copySceneKitAssets: warning: Failed to copy SceneKit assests because scntool failed to process the following resources: /Users/a872414/Library/Developer/Xcode/DerivedData/FootRenderer-cnjerabgjsxlsrergpduhrtaotho/Build/Products/Debug/FootRenderer.app/Contents/Resources/art.scnassets/leg.scn

**Comment by castillejoale** [comment]
@haricharanbole I have the same issue with the same log, it stops after "taking snapshot". I am using macOS 10.15.1

Any luck generating the images?

Regarding the build issue, I had to download leg.scn separately to be able to build the app, for some reason the size of the leg.scn file was very small compared to the ~57Mb

**Comment by castillejoale** [comment]
@haricharanbole found the issue! Calling ".snapshot()" freezes the thread, apparently it needs to be called in the main thread. To fix this I simply wrapped all the code in the didRenderScene method inside a DispatchQueue.main.async {...}

**Comment by haricharanbole** [comment]
@castillejoale I've gone through the same what you've gone through in regards with the scene kit asset. 

I agree with you about ".snapshot()". I've submitted a pull request with my fix. Kindly check it out!

**Comment by haricharanbole** [comment]
Closing the issue since we found the fix.

**Comment by haricharanbole** [comment]
Issue closed.
